# Generated by Django 5.0.6 on 2024-06-19 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="title",
            name="sheet",
        ),
        migrations.AlterModelOptions(
            name="sheet",
            options={
                "ordering": ["name"],
                "verbose_name": "Sheet",
                "verbose_name_plural": "Sheets",
            },
        ),
        migrations.RemoveField(
            model_name="sheet",
            name="sheet_title",
        ),
        migrations.AddField(
            model_name="sheet",
            name="title",
            field=models.CharField(
                default="",
                help_text="The title of the cheat sheet.",
                max_length=200,
                verbose_name="Sheet Title",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="sheet",
            name="name",
            field=models.CharField(
                help_text="The name of the cheat sheet.",
                max_length=200,
                verbose_name="Sheet Name",
            ),
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="The title of the section.",
                        max_length=200,
                        verbose_name="Section Title",
                    ),
                ),
                (
                    "header",
                    models.CharField(
                        blank=True,
                        help_text="An optional header for the section.",
                        max_length=200,
                        verbose_name="Section Header",
                    ),
                ),
                (
                    "sheet",
                    models.ForeignKey(
                        help_text="The cheat sheet this section belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="core.sheet",
                        verbose_name="Sheet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Section",
                "verbose_name_plural": "Sections",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="The title of the content.",
                        max_length=200,
                        verbose_name="Content Title",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="The detailed content message.",
                        verbose_name="Content Message",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        help_text="The section this content belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contents",
                        to="core.section",
                        verbose_name="Section",
                    ),
                ),
            ],
            options={
                "verbose_name": "Content",
                "verbose_name_plural": "Contents",
                "ordering": ["title"],
            },
        ),
        migrations.DeleteModel(
            name="Description",
        ),
        migrations.DeleteModel(
            name="Title",
        ),
    ]
