# Generated by Django 5.0.6 on 2024-06-21 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_title_sheet_alter_sheet_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="content",
            options={
                "ordering": ["ordering"],
                "verbose_name": "Content",
                "verbose_name_plural": "Contents",
            },
        ),
        migrations.AlterModelOptions(
            name="section",
            options={
                "ordering": ["ordering"],
                "verbose_name": "Section",
                "verbose_name_plural": "Sections",
            },
        ),
        migrations.AddField(
            model_name="content",
            name="ordering",
            field=models.SmallIntegerField(
                default=0,
                help_text="Set a number to order the placement of this content, lower mean higher",
                verbose_name="Ordering",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="ordering",
            field=models.SmallIntegerField(
                default=0,
                help_text="Set a number to order the placement of this content, lower mean higher",
                verbose_name="Ordering",
            ),
        ),
    ]
